trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
- group: kasay-propertychanged-variables
  # buildConfiguration: 'Release'
  # Major: '2'
  # Minor: '0'
  # Patch: '2'

steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: 'restore'
    projects: '**/*.sln'

- task: DotNetCoreCLI@2
  displayName: 'dotnet build $(buildConfiguration)'
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration)'
    projects: '**/*.sln'

- task: DotNetCoreCLI@2
  displayName: 'dotnet pack $(buildConfiguration)'
  inputs:
    command: 'pack'
    nobuild: true
    packagesToPack: 'Kasay.PropertyChanged/Kasay.PropertyChanged.csproj'
    versioningScheme: byPrereleaseNumber
    majorVersion: '$(Major)'
    minorVersion: '$(Minor)'
    patchVersion: '$(Patch)'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(build.sourcesdirectory)'
    Contents: '**\bin\$(BuildConfiguration)\**\*.nupkg'
    TargetFolder: '$(build.artifactstagingdirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'